//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.296.
// 
#pragma warning disable 1591

namespace RunInvestorStatements.utiloan {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TasksSoap", Namespace="http://tempuri.org/")]
    public partial class Tasks : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProcessBorrowerStatementsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProcessInvestorStatementsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Tasks() {
            this.Url = global::RunInvestorStatements.Properties.Settings.Default.RunInvestorStatements_utiloan_Tasks;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProcessBorrowerStatementsCompletedEventHandler ProcessBorrowerStatementsCompleted;
        
        /// <remarks/>
        public event ProcessInvestorStatementsCompletedEventHandler ProcessInvestorStatementsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessBorrowerStatements", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ProcessBorrowerStatements(string userName, string password, System.DateTime startDate) {
            object[] results = this.Invoke("ProcessBorrowerStatements", new object[] {
                        userName,
                        password,
                        startDate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessBorrowerStatementsAsync(string userName, string password, System.DateTime startDate) {
            this.ProcessBorrowerStatementsAsync(userName, password, startDate, null);
        }
        
        /// <remarks/>
        public void ProcessBorrowerStatementsAsync(string userName, string password, System.DateTime startDate, object userState) {
            if ((this.ProcessBorrowerStatementsOperationCompleted == null)) {
                this.ProcessBorrowerStatementsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessBorrowerStatementsOperationCompleted);
            }
            this.InvokeAsync("ProcessBorrowerStatements", new object[] {
                        userName,
                        password,
                        startDate}, this.ProcessBorrowerStatementsOperationCompleted, userState);
        }
        
        private void OnProcessBorrowerStatementsOperationCompleted(object arg) {
            if ((this.ProcessBorrowerStatementsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessBorrowerStatementsCompleted(this, new ProcessBorrowerStatementsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProcessInvestorStatements", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ProcessInvestorStatements(string userName, string password, System.DateTime startDate) {
            object[] results = this.Invoke("ProcessInvestorStatements", new object[] {
                        userName,
                        password,
                        startDate});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ProcessInvestorStatementsAsync(string userName, string password, System.DateTime startDate) {
            this.ProcessInvestorStatementsAsync(userName, password, startDate, null);
        }
        
        /// <remarks/>
        public void ProcessInvestorStatementsAsync(string userName, string password, System.DateTime startDate, object userState) {
            if ((this.ProcessInvestorStatementsOperationCompleted == null)) {
                this.ProcessInvestorStatementsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProcessInvestorStatementsOperationCompleted);
            }
            this.InvokeAsync("ProcessInvestorStatements", new object[] {
                        userName,
                        password,
                        startDate}, this.ProcessInvestorStatementsOperationCompleted, userState);
        }
        
        private void OnProcessInvestorStatementsOperationCompleted(object arg) {
            if ((this.ProcessInvestorStatementsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProcessInvestorStatementsCompleted(this, new ProcessInvestorStatementsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ProcessBorrowerStatementsCompletedEventHandler(object sender, ProcessBorrowerStatementsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessBorrowerStatementsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessBorrowerStatementsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ProcessInvestorStatementsCompletedEventHandler(object sender, ProcessInvestorStatementsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProcessInvestorStatementsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProcessInvestorStatementsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591